kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: read-service-global
subjects:
- kind: ServiceAccount
  name: route53-kubernetes
  namespace: {{ .Release.Namespace }}
  # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io